name: promql
description: Prometheus Query CLI
repo: nalbury/promql-cli
version:
  latest: v0.2.0 # renovate: datasource=github-releases depName=nalbury/promql-cli
  command: promql --version
  filter: ^promql
  pattern: s/^promql\sversion\s(.+)$/\1/
tags:
- prometheus
- promql
install: |
  build_containerized golang <<EOF
  git clone https://github.com/nalbury/promql-cli
  cd promql-cli
  git checkout "${requested_version}"
  go mod download
  go build -o promql .
  cp promql /
  EOF
  extract_file_from_container promql
