name: tracee
description: Container and system event tracing using eBPF
repo: aquasecurity/tracee
version:
  latest: v0.2.1 # renovate: datasource=github-releases depName=aquasecurity/tracee
tags:
- container
- ebpf
- security
- tracing
