name: flarectl
description: A CLI application for interacting with a Cloudflare account
repo: cloudflare/cloudflare-go
links:
  - text: Usage
    url: https://github.com/cloudflare/cloudflare-go/tree/master/cmd/flarectl
  - text: CloudFlare API
    url: https://api.cloudflare.com/
version:
  latest: v0.13.5 # renovate: datasource=github-releases depName=cloudflare/cloudflare-go
  command: flarectl --version
  filter: ^flarectl
  pattern: s/^flarectl\sversion\s(.+)$/\1/
tags:
  - dns
install:
  script: |-
    github_install \
        --repo cloudflare/cloudflare-go \
        --match suffix \
        --asset _linux_amd64.tar.xz \
        --type xz \
        --include flarectl
