name: hcloud
description: A command-line interface for Hetzner Cloud
repo: hetznercloud/cli
version:
  latest: v1.20.0 # renovate: datasource=github-releases depName=hetznercloud/cli
tags:
- hetzner
- cloud
