name: bin
description: Effortless binary manager
repo: marcosnils/bin
version:
  latest: v0.2.1 # renovate: datasource=github-releases depName=marcosnils/bin
  command: bin --version
  filter: ^bin version
  pattern: s/^bin\sversion\s(.+)$/v\1/
tags:
- shell
