name: renovate
description: Universal dependency update tool that fits into your workflows
repo: renovatebot/renovate
version:
  latest: 23.67.3 # renovate: datasource=github-releases depName=renovatebot/renovate
  command: renovate --version
  filter: ^[[:digit:]]+
  pattern: ^(.+)$
tags:
- docker
- container
- interface
- ui
