name: kube-capacity
description: A simple CLI that provides an overview of the resource requests, limits, and utilization in a Kubernetes cluster
repo: robscott/kube-capacity
tags:
- kubernetes
- k8s
- capacity
- resources
- requests
- limits
- utilization
