name: faas-cli
description: Official CLI for OpenFaaS
repo: openfaas/faas-cli
links:
- text: Homepage
  url: https://www.openfaas.com/
version:
  latest: 0.12.14 # renovate: datasource=github-releases depName=openfaas/faas-cli
tags:
- openfaas
- function
- service
- serverless
