name: norouter
description: IP-over-Stdio. The easiest multi-host & multi-cloud networking ever. No root privilege is required
repo: norouter/norouter
version:
  latest: v0.5.0 # renovate: datasource=github-releases depName=norouter/norouter
  command: norouter --version
  filter: ^norouter
  pattern: s/^norouter\sversion\s(.+)$/v\1/
tags:
  - network
install:
  script: |-
    github_install \
        --repo norouter/norouter \
        --match name \
        --asset norouter-Linux-x86_64 \
        --type binary \
        --name norouter
