name: conmon
description: An OCI container runtime monitor
repo: containers/conmon
version:
  latest: v2.0.21 # renovate: datasource=github-releases depName=containers/conmon
  command: conmon --version
  filter: ^conmon
  pattern: s/^conmon\sversion\s(.+)$/v\1/
tags:
- container
- runtime
files:
- Dockerfile
