name: ocictl
description: A tool to build OCI compliant images
repo: ocibuilder/ocibuilder
version:
  latest: 0.1.1 # renovate: datasource=github-releases depName=ocibuilder/ocibuilder
tags:
- container
- image
- oci
install: |
  github_get_release ocibuilder/ocibuilder | \
      github_resolve_assets | \
      github_select_asset_by_name ocictl-linux-amd64.tar.gz | \
      github_get_asset_download_url | \
      download_file | \
      ${SUDO} tar -xzC "${TARGET_BIN}" --strip-components=2 ./ocictl/ocictl
