name: yaml-patch
description: A library to apply YAML versions of RFC6902 patches
repo: krishicks/yaml-patch
version:
  latest: v0.0.10 # renovate: datasource=github-releases depName=krishicks/yaml-patch
tags:
- yaml
- patch
