name: lolcat
description: Rainbows and unicorns
repo: busyloop/lolcat
version:
  latest: 100.0.1 # renovate: datasource=npm depName=lolcat
  command: lolcat --version
  filter: ^lolcat
  pattern: s/^lolcat\s(\S+)\s.+$/\1/
tags:
  - shell
install:
  script: install_ruby_module lolcat
