name: kustomize
description: Customization of kubernetes YAML configurations
repo: kubernetes-sigs/kustomize
links:
- text: Homepage
  url: https://kustomize.io/
version:
  latest: kustomize/v3.8.6 # renovate: datasource=github-releases depName=kubernetes-sigs/kustomize versioning=regex:^kustomize\/v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
  command: kustomize version
  filter: ^{Version
  pattern: s/^\{Version:(\S+)\s.+$/\1/
tags:
- kubernetes
- k8s
- template
- configuration
- substitution
- expansion
- package
- yaml
