name: k3c
description: Lightweight local container engine for container development
repo: rancher/k3c
version:
  latest: v0.2.1 # renovate: datasource=github-releases depName=rancher/k3c
  command: k3c --version
  filter: ^k3c
  pattern: s/^k3c\sversion\s(\S+)\s.+$/\1/
tags:
- container
- runtime
- build
- builder
- image
install: |
  github_install \
      --repo rancher/k3c \
      --match name \
      --asset k3c-linux-amd64 \
      --type binary \
      --name k3c
