name: k3c
description: Lightweight local container engine for container development
repo: rancher/k3c
version:
  latest: v0.2.1 # renovate: datasource=github-releases depName=rancher/k3c
tags:
- container
- runtime
- build
- builder
- image
