name: toast
description: Containerize your development and continuous integration environments
repo: stepchowfun/toast
tags:
- pipeline
- continuous
- ci/cd
- integration
- delivery
- deployment
- container
