name: toast
description: Containerize your development and continuous integration environments
repo: stepchowfun/toast
version:
  latest: v0.32.0 # renovate: datasource=github-releases depName=stepchowfun/toast
  command: toast --version
  filter: ^Toast
  pattern: s/^Toast\s(.+)$/v\1/
tags:
  - pipeline
  - continuous
  - ci/cd
  - integration
  - delivery
  - deployment
  - container
install:
  script: |-
    github_install \
        --repo stepchowfun/toast \
        --match name \
        --asset toast-x86_64-unknown-linux-gnu \
        --type binary \
        --name toast
