name: direnv
description: Unclutter your .profile
repo: direnv/direnv
links:
- text: Homepage
  url: https://direnv.net/
version:
  latest: v2.23.1 # renovate: datasource=github-releases depName=direnv/direnv
tags:
- shell
- configuration
files:
- profile.d.direnv.sh
