name: nvm
description: Node Version Manager - POSIX-compliant bash script to manage multiple active node.js versions
repo: nvm-sh/nvm
version:
  latest: v0.37.0 # renovate: datasource=github-releases depName=nvm-sh/nvm
  command: nvm --version
  filter: ^[[:digit:]]
  pattern: s/^(.+)$/v\1/
tags:
- node
- nodejs
- version
- manager
- version manager
files:
- name: profile.d.nvm.sh
  content: |
    #!/bin/bash
    export NVM_DIR="${TARGET_BASE}/nvm"
    source "${NVM_DIR}/nvm.sh"
