name: nvm
description: Node Version Manager - POSIX-compliant bash script to manage multiple active node.js versions
repo: nvm-sh/nvm
version:
  latest: v0.37.0 # renovate: datasource=github-releases depName=nvm-sh/nvm
  command: nvm --version
  filter: ^[[:digit:]]
  pattern: s/^(.+)$/v\1/
tags:
- node
- nodejs
- version
- manager
- version manager
install: |
  if ! test -d "${TARGET_BASE}/nvm"; then
      ${SUDO} git clone https://github.com/nvm-sh/nvm "${TARGET_BASE}/nvm"
  fi
  pushd "${TARGET_BASE}/nvm"
  git checkout "${requested_version}"
  popd

  get_file "${PACKAGE}" profile.d.nvm.sh | \
      TARGET_BASE="${TARGET_BASE}" envsubst '${TARGET_BASE}' | \
      store_file nvm.sh /etc/profile.d
files:
- name: profile.d.nvm.sh
  content: |
    #!/bin/bash
    export NVM_DIR="${TARGET_BASE}/nvm"
    source "${NVM_DIR}/nvm.sh"
