name: nvm
description: Node Version Manager - POSIX-compliant bash script to manage multiple active node.js versions
repo: nvm-sh/nvm
version:
  latest: v0.36.0 # renovate: datasource=github-releases depName=nvm-sh/nvm
tags:
- node
- nodejs
- version
- manager
- version manager
files:
- profile.d.nvm.sh
