name: compose-cli
description: Easily run your Compose application to the cloud with compose-cli
repo: docker/compose-cli
version:
  latest: v1.0.3 # renovate: datasource=github-releases depName=docker/compose-cli
tags:
  - docker
  - compose
  - cli
  - plugin
  - ecs
  - azure
  - aws
  - aci
  - container
install:
  script: |-
    ${SUDO} ln -sf "${TARGET_BIN}/docker" "${TARGET_BIN}/com.docker.cli"

    github_get_release docker/compose-cli | \
        github_resolve_assets | \
        github_select_asset_by_name docker-linux-amd64.tar.gz | \
        github_get_asset_download_url | \
        download_file | \
        TARGET_BIN="${temporary_directory}" untar_file --strip-components=1 docker/docker
    ${SUDO} mv docker "${TARGET_BIN}/compose-cli"

    echo "########################################"
    echo "### While in beta, this is installed in"
    echo "###   ${TARGET_BIN}/compose-cli"
    echo "########################################"
