name: compose-cli
description: Easily run your Compose application to the cloud with compose-cli
repo: docker/compose-cli
version:
  latest: v1.0.1 # renovate: datasource=github-releases depName=docker/compose-cli
tags:
- docker
- compose
- cli
- plugin
- ecs
- azure
- aws
- aci
- container
