name: aws-cli
description: Universal Command Line Interface for Amazon Web Services
repo: aws/aws-cli
links:
- text: Homepage
  url: https://aws.amazon.com/cli/
version:
  latest: 1.18.170 # renovate: datasource=github-tags depName=aws/aws-cli
tags:
- aws
- cloud
