name: wksctl
description: Open Source Weaveworks Kubernetes System
repo: weaveworks/wksctl
version:
  latest: v0.9.0-alpha.4 # renovate: datasource=github-releases depName=weaveworks/wksctl
  command: wksctl version
  filter: ^[[:digit:]]
  pattern: s/^(.+)$/v\1/
tags:
- kubernetes
- k8s
- cluster
- bootstrap
