name: cni
description: Some reference and example networking plugins
repo: containernetworking/plugins
version:
  latest: v0.8.7 # renovate: datasource=github-releases depName=containernetworking/plugins
  command: |
    /opt/cni/bin/loopback --version 2>&1
  filter: ^CNI
  pattern: s/^CNI\sloopback\splugin\s(.+)$/\1/
tags:
- kubernetes
- k8s
- network
- plugin
- cni
install: |
  ${SUDO} mkdir -p /opt/cni/bin
  github_find_latest_release containernetworking/plugins | \
      github_resolve_assets | \
      run_filters \
          "github_select_asset_by_prefix cni-plugins-linux-amd64" \
          "github_select_asset_by_suffix .tgz" | \
      github_get_asset_download_url | \
      download_file | \
      ${SUDO} tar -xzC /opt/cni/bin/
