name: cni
description: Some reference and example networking plugins
repo: containernetworking/plugins
version:
  latest: v0.8.7 # renovate: datasource=github-releases depName=containernetworking/plugins
tags:
- kubernetes
- k8s
- network
- plugin
- cni
