name: bit
description: Bit is a modern Git CLI
repo: chriswalz/bit
version:
  latest: v0.9.11 # renovate: datasource=github-releases depName=chriswalz/bit
tags:
- pipeline
- continuous
- ci/cd
- integration
- delivery
- deployment
- container
