name: gvisor
description: Application Kernel for Containers
repo: google/gvisor
version:
  latest: release-20201030.0 # renovate: datasource=github-tags depName=google/gvisor versioning=regex:^release-(?<major>\d+)\.(?<minor>\d+)$
  command: runsc --version
  filter: ^runsc
  pattern: s/^runsc\sversion\s(.+)$/\1/
tags:
- container
- runtime
- security
install: |
  echo "https://storage.googleapis.com/gvisor/releases/release/latest/runsc" | \
      download_file | \
      store_file runsc | \
      make_executable

  ${SUDO} runsc install
