name: kube-score
description: Kubernetes object analysis with recommendations for improved reliability and security
repo: zegl/kube-score
version:
  latest: v1.9.0 # renovate: datasource=github-releases depName=zegl/kube-score
tags:
- kubernetes
- k8s
- security
