name: kube-score
description: Kubernetes object analysis with recommendations for improved reliability and security
repo: zegl/kube-score
version:
  latest: v1.10.0 # renovate: datasource=github-releases depName=zegl/kube-score
  command: kube-score version
  filter: ^kube-score
  pattern: s/^kube-score\sversion:\s([^,]+),.+$/v\1/
tags:
- kubernetes
- k8s
- security
