name: jid
description: json incremental digger
repo: simeji/jid
version:
  latest: v0.7.6 # renovate: datasource=github-releases depName=simeji/jid
  command: jid --version
  filter: ^jid
  pattern: s/^jid\sversion\s(.+)$/\1/
tags:
- json
install: |
  github_install \
      --repo simeji/jid \
      --match name \
      --asset jid_linux_amd64.zip \
      --type zip \
      --include jid
