name: yq
description: yq is a portable command-line YAML processor
repo: mikefarah/yq
version:
  latest: 3.4.1 # renovate: datasource=github-releases depName=mikefarah/yq
  command: yq --version
  filter: ^yq
  pattern: s/^yq\sversion\s(.+)$/\1/
tags:
- yaml
- query
- processor
install:
  docker: false
  script: |
    github_install \
        --repo mikefarah/yq \
        --match name \
        --asset yq_linux_amd64 \
        --type binary \
        --name yq

    yq shell-completion | \
        store_completion yq
