name: yq
description: yq is a portable command-line YAML processor
repo: mikefarah/yq
version:
  latest: 3.4.1 # renovate: datasource=github-releases depName=mikefarah/yq
tags:
- yaml
- query
- processor
