name: kind
description: Kubernetes IN Docker - local clusters for testing Kubernetes
repo: kubernetes-sigs/kind
links:
- text: Homepage
  url: https://kind.sigs.k8s.io/
version:
  latest: v0.9.0 # renovate: datasource=github-releases depName=kubernetes-sigs/kind
tags:
- kubernetes
- k8s
- dind
- docker
- cluster
- bootstrap
