name: kind
description: Kubernetes IN Docker - local clusters for testing Kubernetes
repo: kubernetes-sigs/kind
links:
- text: Homepage
  url: https://kind.sigs.k8s.io/
version:
  latest: v0.9.0 # renovate: datasource=github-releases depName=kubernetes-sigs/kind
  command: kind --version
  filter: ^kind
  pattern: s/^kind\sversion\s(.+)$/v\1/
tags:
- kubernetes
- k8s
- dind
- docker
- cluster
- bootstrap
install: |
  github_install \
      --repo kubernetes-sigs/kind \
      --match name \
      --asset kind-linux-amd64 \
      --type binary \
      --name kind

  kind completion bash | \
      store_completion kind
