name: sslyze
description: Fast and powerful SSL/TLS scanning library
repo: nabla-c0d3/sslyze
version:
  latest: 3.0.8 # renovate: datasource=github-releases depName=nabla-c0d3/sslyze
tags:
- ssl
- tls
- scan
- test
- quality
