name: sslyze
description: Fast and powerful SSL/TLS scanning library
repo: nabla-c0d3/sslyze
version:
  latest: 3.0.8 # renovate: datasource=github-releases depName=nabla-c0d3/sslyze
  command: sslyze --version
  filter: ^[[:digit:]]
  pattern: s/^(.+)$/\1/
tags:
  - ssl
  - tls
  - scan
  - test
  - quality
files:
  - name: profile.d.sslyze.sh
    content: |
      #!/bin/bash
      alias sslyze="python3 -m sslyze"
install:
  script: |-
    install_python_module sslyze

    get_file sslyze profile.d.sslyze.sh | \
        TARGET_BASE=${TARGET_BASE} envsubst '${TARGET_BASE}' | \
        store_file sslyze.sh /etc/profile.d/
