name: conftest
description: Write tests against structured configuration data using the Open Policy Agent Rego query language
repo: open-policy-agent/conftest
links:
- text: Homepage
  url: https://conftest.dev/
version:
  latest: v0.21.0 # renovate: datasource=github-releases depName=open-policy-agent/conftest
  command: conftest --version
  filter: |
    ^Version:
  pattern: s/^Version:\s(.+)$/v\1/
tags:
- validation
- schema
- configuration
- test
- query
- rego
install: |
  github_install \
      --repo open-policy-agent/conftest \
      --match suffix \
      --asset _Linux_x86_64.tar.gz \
      --type tarball \
      --include conftest
