name: json-patch
description: A Go library to apply RFC6902 patches and create and apply RFC7386 patches
repo: evanphx/json-patch
version:
  latest: v5.0.0 # renovate: datasource=github-releases depName=evanphx/json-patch
tags:
- json
- patch
