name: regctl
description: Client interface for the registry API
repo: regclient/regclient
version:
  latest: v0.0.4 # renovate: datasource=github-releases depName=regclient/regclient
tags:
- docker
- container
- registry
