name: regctl
description: Client interface for the registry API
repo: regclient/regclient
version:
  latest: v0.1.0 # renovate: datasource=github-releases depName=regclient/regclient
tags:
  - docker
  - container
  - registry
install:
  docker: false
  script: |-
    github_install \
        --repo regclient/regclient \
        --match name \
        --asset regctl-linux-amd64 \
        --type binary \
        --name regctl
