name: regctl
description: Client interface for the registry API
repo: regclient/regclient
version:
  latest: v0.0.5 # renovate: datasource=github-releases depName=regclient/regclient
tags:
- docker
- container
- registry
install: |
  build_containerized golang <<EOF
  git clone https://github.com/regclient/regclient
  cd regclient
  git checkout ${requested_version}
  go build -ldflags "-linkmode external -extldflags -static" -a -o regctl ./cmd/regctl/
  cp regctl /
  EOF
  extract_file_from_container regctl
