name: yamllint
description: A linter for YAML files
repo: adrienverge/yamllint
version:
  latest: v1.25.0 # renovate: datasource=github-releases depName=adrienverge/yamllint
  command: yamllint --version
  filter: ^yamllint
  pattern: s/^yamllint\s(.+)$/v\1/
tags:
- yaml
- linter
- test
- quality
files:
- Dockerfile
