name: rootlesskit
description: Linux-native "fake root" for rootless containers
repo: rootless-containers/rootlesskit
version:
  latest: v0.11.1 # renovate: datasource=github-releases depName=rootless-containers/rootlesskit
  command: rootlesskit --version
  filter: ^rootlesskit
  pattern: s/^rootlesskit\sversion\s(.+)$/v\1/
tags:
  - container
  - rootless
install:
  script: |-
    github_install \
        --repo rootless-containers/rootlesskit \
        --match name \
        --asset rootlesskit-x86_64.tar.gz \
        --type tarball
