name: ksort
description: Sort manifest files in a proper order by Kind
repo: superbrothers/ksort
version:
  latest: v0.4.1 # renovate: datasource=github-releases depName=superbrothers/ksort
tags:
- kubernetes
- k8s
install: |
  github_install \
      --repo superbrothers/ksort \
      --match name \
      --asset ksort-linux-amd64.tar.gz \
      --type tarball \
      --include ksort
