name: arkade
description: Your one-stop CLI for Kubernetes
repo: alexellis/arkade
version:
  latest: 0.6.17 # renovate: datasource=github-releases depName=alexellis/arkade
  command: arkade version
  filter: Version
  pattern: Version:\s(.+)
tags:
- kubernetes
- k8s
