name: lazygit
description: Simple terminal UI for git commands
repo: jesseduffield/lazygit
version:
  latest: v0.23.7 # renovate: datasource=github-releases depName=jesseduffield/lazygit
  command: lazygit --version
  filter: version=
  pattern: s/^.+,\sversion=([^,]+),\s.+$/v\1/
tags:
  - git
  - ui
install:
  script: |-
    github_install \
        --repo jesseduffield/lazygit \
        --match suffix \
        --asset _Linux_x86_64.tar.gz \
        --type tarball \
        --include lazygit
