name: docker-shell
description: A simple interactive prompt for docker
repo: Trendyol/docker-shell
version:
  latest: v1.3.1 # renovate: datasource=github-tags depName=Trendyol/docker-shell
tags:
  - docker
  - container
  - ui
install:
  docker: true
  script: |-
    build_containerized golang <<EOF
    curl -sL "https://github.com/Trendyol/docker-shell/archive/${requested_version}.tar.gz" | \
        ${SUDO} tar -tvzC /tmp
    cd "/tmp/docker-shell-${requested_version#v}"
    go build -o docker-shell .
    cp docker-shell /
    EOF
    extract_file_from_container docker-shell
