name: containerssh
description: An SSH server that launches containers
repo: ContainerSSH/ContainerSSH
version:
  latest: 0.4.0-PR2 # renovate: datasource=github-releases depName=ContainerSSH/ContainerSSH
tags:
- encryption
- security
