name: semver-tool
description: semver bash implementation
repo: fsaintjacques/semver-tool
version:
  latest: 3.1.0 # renovate: datasource=github-tags depName=fsaintjacques/semver-tool
  command: semver --version
  filter: ^semver
  pattern: s/^semver:\s(.+)$/\1/
tags:
- shell
- semver
