name: docker
description: Docker Community Edition
repo: docker/docker-ce
links:
- text: Homepage
  url: https://www.docker.com/
version:
  latest: v19.03.13 # renovate: datasource=github-releases depName=docker/docker-ce
tags:
- docker
- container
- build
- builder
- runtime
- image
