name: docker
description: Docker Community Edition
repo: docker/docker-ce
links:
- text: Homepage
  url: https://www.docker.com/
version:
  latest: v19.03.13 # renovate: datasource=github-releases depName=docker/docker-ce versioning=regex:^v(?<major>\d+?)\.(?<minor>\d+?)\.(?<patch>\d+?)(-(?<prerelease>.+?))?$
  command: docker --version
  filter: ^Docker
  pattern: s/^Docker\sversion\s([^,]+),.+$/v\1/
tags:
- docker
- container
- build
- builder
- runtime
- image
install: |
  github_find_latest_release docker/docker-ce | \
      jq --raw-output '.name' | \
      xargs -I{} curl --location --fail https://download.docker.com/linux/static/stable/x86_64/docker-{}.tgz | \
      untar_file --strip-components=1

  github_find_latest_release docker/docker-ce | \
      jq --raw-output '.tag_name' | \
      xargs -I{} curl --location --fail https://raw.githubusercontent.com/docker/cli/{}/contrib/completion/bash/docker | \
      store_completion docker

  : "${DOCKER_CONFIG:=${HOME}/.docker}"
  if ! test -d "${DOCKER_CONFIG}"; then
      mkdir --parents "${DOCKER_CONFIG}"
  fi

  if ! test -f "${DOCKER_CONFIG}/config.json"; then
      echo "{}" >"${DOCKER_CONFIG}/config.json"
  fi

  cp "${DOCKER_CONFIG}/config.json" "${DOCKER_CONFIG}/config.json.bak"
  jq '. + {"features":{"buildkit":true}}' "${DOCKER_CONFIG}/config.json.bak" >"${DOCKER_CONFIG}/config.json"
