name: inletsctl
description: Cloud Native Tunnel for APIs
repo: inlets/inlets
links:
- text: Homepage
  url: https://inlets.dev/
version:
  latest: 0.6.4 # renovate: datasource=github-releases depName=inlets/inletsctl
  command: inletsctl version
  filter: ^Version
  pattern: s/^Version:\s(.+)$/\1/
tags:
- kubernetes
- k8s
- tunnel
