name: docker-compose
description: Define and run multi-container applications with Docker
repo: docker/compose
links:
- text: Specification
  url: https://compose-spec.io/
version:
  latest: 1.27.4 # renovate: datasource=github-releases depName=docker/compose
tags:
- docker
- container
- compose
