name: docker-compose
description: Define and run multi-container applications with Docker
repo: docker/compose
links:
- text: Specification
  url: https://compose-spec.io/
version:
  latest: 1.27.4 # renovate: datasource=github-releases depName=docker/compose
  command: docker-compose version
  filter: ^docker-compose
  pattern: s/^docker-compose\sversion\s([^,]+),.+$/\1/
tags:
- docker
- container
- compose
install: |
  github_install \
      --name docker-compose \
      --repo docker/compose \
      --match name \
      --asset docker-compose-Linux-x86_64 \
      --type binary

  ${SUDO} mkdir -p "${TARGET}/etc/bash_completion.d"
  github_get_release docker/compose | \
      jq --raw-output '.tag_name' | \
      xargs -I{} curl --location --fail https://github.com/docker/compose/raw/{}/contrib/completion/bash/docker-compose | \
      store_completion docker-compose
