name: stargz-snapshotter
description: Fast docker image distribution plugin for containerd, based on CRFS/stargz
repo: containerd/stargz-snapshotter
version:
  latest: v0.1.0 # renovate: datasource=github-releases depName=containerd/stargz-snapshotter
tags:
  - container
  - runtime
  - registry
install:
  docker: true
  script: |-
    build_containerized golang <<EOF
    git clone https://github.com/containerd/stargz-snapshotter
    cd stargz-snapshotter
    git checkout ${requested_version}
    CGO_ENABLED=0 make GO_BUILD_FLAGS=-ldflags="-extldflags=-static"
    cp out/* /
    EOF
    extract_file_from_container ctr-remote
    extract_file_from_container containerd-stargz-grpc