name: skopeo
description: Work with remote images registries - retrieving information, images, signing content
repo: containers/skopeo
version:
  latest: v1.2.0 # renovate: datasource=github-releases depName=containers/skopeo
tags:
- container
- registry
- image
