name: envsub
description: An alternative envsubst that allows for `${foo:-default}` expansion too
repo: stephenc/envsub
version:
  latest: 0.1.1 # renovate: datasource=github-releases depName=stephenc/envsub
tags:
- shell
- substitution
- expansion
- variables
