name: krew
description: Find and install kubectl plugins
repo: kubernetes-sigs/krew
links:
  - text: Homepage
    url: https://krew.sigs.k8s.io/
version:
  latest: v0.4.0 # renovate: datasource=github-releases depName=kubernetes-sigs/krew
  command: krew version
  filter: ^GitTag
  pattern: s/^GitTag\s+(.+)$/\1/
tags:
  - kubernetes
  - k8s
  - plugins
install:
  script: |-
    github_get_release kubernetes-sigs/krew | \
        github_resolve_assets | \
        github_select_asset_by_name krew.tar.gz | \
        github_get_asset_download_url | \
        download_file | \
        untar_file ./krew-linux_amd64
    rename_file krew-linux_amd64 krew

    krew update
    if ! krew index list | grep --quiet kvaps; then
        krew index add kvaps https://github.com/kvaps/krew-index
    fi

    krew install \
        access-matrix \
        advise-psp \
        cert-manager \
        debug \
        doctor \
        exec-as \
        get-all \
        images \
        neat \
        net-forward \
        node-shell \
        rbac-lookup \
        rbac-view \
        reap \
        resource-capacity \
        score \
        sniff \
        sort-manifests \
        status \
        sudo \
        tap \
        tmux-exec \
        tree \
        view-allocations \
        who-can \
        whoami \
        kvaps/use

    kubectl use -completion | \
        store_completion kubectl-use
