name: krew
description: Find and install kubectl plugins
repo: kubernetes-sigs/krew
links:
- text: Homepage
  url: https://krew.sigs.k8s.io/
version:
  latest: v0.4.0 # renovate: datasource=github-releases depName=kubernetes-sigs/krew
  command: krew version
  filter: ^GitTag
  pattern: s/^GitTag\s+(.+)$/\1/
tags:
- kubernetes
- k8s
- plugins
