name: trivy
description: A Simple and Comprehensive Vulnerability Scanner for Containers, Suitable for CI
repo: aquasecurity/trivy
version:
  latest: v0.12.0 # renovate: datasource=github-releases depName=aquasecurity/trivy
  command: trivy --version
  filter: ^Version
  pattern: s/^Version:\s(.+)$/v\1/
tags:
  - container
  - security
  - scan
  - test
  - quality
install:
  script: |-
    github_install \
        --repo aquasecurity/trivy \
        --match suffix \
        --asset _Linux-64bit.tar.gz \
        --type tarball \
        --include trivy

    if ! test -d "${HOME}/.cache/trivy"; then
        trivy image --download-db-only
    fi
