name: trivy
description: A Simple and Comprehensive Vulnerability Scanner for Containers, Suitable for CI
repo: aquasecurity/trivy
version:
  latest: v0.12.0 # renovate: datasource=github-releases depName=aquasecurity/trivy
tags:
- container
- security
- scan
- test
- quality
