name: asciinema
description: Record and share your terminal sessions
repo: asciinema/asciinema
links:
- text: Homepage
  url: https://asciinema.org/
version:
  latest: v2.0.2 # renovate: datasource=github-releases depName=asciinema/asciinema
tags:
- shell
- record
- cast
- screen
