name: java
description: (cross-platform) Java Version Manager
repo: shyiko/jabba
version:
  #latest: 0.11.2 # renovate: datasource=github-releases depName=shyiko/jabba
  command: java -version 2>&1
  filter: ^openjdk
  pattern: s/^openjdk\sversion\s\"([^\"]+)\".+$/\1/
tags:
  - java
  - version
  - manager
  - version manager
install:
  script: |-
    require jabba
    source /etc/profile.d/jabba.sh
    ${SUDO} bash --login -c "jabba install openjdk@1 && jabba use openjdk@1 && jabba alias default openjdk@1"

    get_file java profile.d.java.sh | \
        TARGET_BASE=${TARGET_BASE} envsubst '${TARGET_BASE}' | \
        store_file java.sh /etc/profile.d
files:
- name: profile.d.java.sh
  content: |
    #!/bin/bash
    export JAVA_HOME="${TARGET_BASE}/jabba/jdk/default"
    export PATH="${TARGET_BASE}/jabba/jdk/default/bin:${PATH}"
