name: java
description: (cross-platform) Java Version Manager
repo: shyiko/jabba
version:
  latest: 1.15.0-1
  command: ${TARGET_BASE}/jabba/jdk/default/bin/java --show-version
  filter: ^openjdk
  pattern: s/^openjdk\s(\S+)\s.+/\1/;s/^([^.]+)\.[^.]+\.([^.]+)$/1.\1.0-\2/
tags:
  - java
  - version
  - manager
  - version manager
install:
  script: |-
    require jabba
    source /etc/profile.d/jabba.sh
    ${SUDO} bash --login -c "jabba install openjdk@1 && jabba use openjdk@1 && jabba alias default openjdk@1"

    get_file java profile.d.java.sh | \
        TARGET_BASE=${TARGET_BASE} envsubst '${TARGET_BASE}' | \
        store_file java.sh /etc/profile.d
files:
- name: profile.d.java.sh
  content: |
    #!/bin/bash
    export JAVA_HOME="${TARGET_BASE}/jabba/jdk/default"
    export PATH="${TARGET_BASE}/jabba/jdk/default/bin:${PATH}"
