name: shellcheck
description: A static analysis tool for shell scripts
repo: koalaman/shellcheck
version:
  latest: v0.7.1 # renovate: datasource=github-releases depName=koalaman/shellcheck
  command: shellcheck --version
  filter: ^version
  pattern: s/^version:\s(.+)$/v\1/
tags:
- shell
- quality
- test
- validate
- analysis
install: |
  github_find_latest_release koalaman/shellcheck | \
      github_resolve_assets | \
      github_select_asset_by_suffix .linux.x86_64.tar.xz | \
      github_get_asset_download_url | \
      download_file | \
      ${SUDO} tar -xJC "${TARGET_BIN}" --strip-components 1 --wildcards "*/shellcheck"
