name: kapp
description: kapp is a simple deployment tool focused on the concept of "Kubernetes application" — a set of resources with the same label
repo: k14s/kapp
links:
- text: Homepage
  url: https://carvel.dev/
version:
  latest: v0.34.0 # renovate: datasource=github-releases depName=k14s/kapp
tags:
- kubernetes
- k8s
- ui
- package
