name: bat
description: A cat(1) clone with wings
repo: sharkdp/bat
version:
  latest: v0.16.0 # renovate: datasource=github-releases depName=sharkdp/bat
  command: bat --version
  filter: ^bat
  pattern: s/^bat\s(.+)$/v\1/
tags:
- console
