name: bat
description: A cat(1) clone with wings
repo: sharkdp/bat
version:
  latest: v0.16.0 # renovate: datasource=github-releases depName=sharkdp/bat
  command: bat --version
  filter: ^bat
  pattern: s/^bat\s(.+)$/v\1/
tags:
- console
install: |
  github_find_latest_release sharkdp/bat | \
      github_resolve_assets | \
      github_select_asset_by_suffix -x86_64-unknown-linux-gnu.tar.gz | \
      github_get_asset_download_url | \
      download_file \
      >"${temporary_directory}/bat.tar.gz"

  ${SUDO} tar -xz -f "${temporary_directory}/bat.tar.gz" -C "${TARGET_BIN}" --wildcards --strip-components=1 "*/bat"
  ${SUDO} tar -xz -f "${temporary_directory}/bat.tar.gz" -C "${TARGET_BASE}/man/man1" --wildcards --strip-components=1 "*/bat.1"
