name: kubeseal
description: A Kubernetes controller and tool for one-way encrypted Secrets
repo: bitnami-labs/sealed-secrets
version:
  latest: v0.13.1 # renovate: datasource=github-releases depName=bitnami-labs/sealed-secrets
tags:
- kubernetes
- k8s
- secrets
- security
