name: kubeseal
description: A Kubernetes controller and tool for one-way encrypted Secrets
repo: bitnami-labs/sealed-secrets
version:
  latest: v0.13.1 # renovate: datasource=github-releases depName=bitnami-labs/sealed-secrets
  command: kubeseal --version
  filter: ^kubeseal
  pattern: s/^kubeseal\sversion:\s(.+)\+.+$/\1/
tags:
  - kubernetes
  - k8s
  - secrets
  - security
install:
  script: |-
    github_install \
        --repo bitnami-labs/sealed-secrets \
        --match name \
        --asset kubeseal-linux-amd64 \
        --type binary \
        --name kubeseal
