name: oras
description: OCI Registry As Storage
repo: deislabs/oras
links:
- text: OCI artifacts
  url: https://github.com/opencontainers/artifacts
version:
  latest: v0.8.1 # renovate: datasource=github-releases depName=deislabs/oras
  command: oras version
  filter: ^Version
  pattern: s/^Version:\s+(\S+)$/v\1/
tags:
- oci
- registry
- artifact
install: |
  github_install \
      --repo deislabs/oras \
      --match suffix \
      --asset _linux_amd64.tar.gz \
      --type tarball \
      --include oras
