name: rbenv
description: Groom your app’s Ruby environment
repo: rbenv/rbenv
version:
  latest: v1.1.2 # renovate: datasource=github-releases depName=rbenv/rbenv
  command: rbenv --version
  filter: ^rbenv
  pattern: s/^rbenv\s([^-]+)-.+$/v\1/
tags:
- ruby
- version
- manager
- version manager
files:
- name: Dockerfile
  content: |
    FROM ubuntu:20.04@sha256:1d7b639619bdca2d008eca2d5293e3c43ff84cbee597ff76de3b7a7de3e84956
    ENV DEBIAN_FRONTEND=noninteractive
    RUN apt-get update \
    && apt-get -y install \
            autoconf \
            bison \
            build-essential \
            libssl-dev \
            libyaml-dev \
            libreadline6-dev \
            zlib1g-dev \
            libncurses5-dev \
            libffi-dev \
            libgdbm6 \
            libgdbm-dev \
            libdb-dev \
            curl \
            ca-certificates
- name: profile.d.rbenv.sh
  content: |
    #!/bin/sh
    export RBENV_ROOT="${TARGET_BASE}/rbenv"
    export PATH="${RBENV_ROOT}/shims:${RBENV_ROOT}/bin:${PATH}"
