name: rbenv
description: Groom your app’s Ruby environment
repo: rbenv/rbenv
version:
  latest: v1.1.2 # renovate: datasource=github-releases depName=rbenv/rbenv
tags:
- ruby
- version
- manager
- version manager
files:
- Dockerfile
