name: kdo
description: Deployless Development on Kubernetes
repo: stepro/kdo
version:
  latest: v0.6.1 # renovate: datasource=github-tags depName=stepro/kdo
  command: kdo --version
  filter: ^kdo
  pattern: s/^kdo\sversion\s(.+)$/v\1/
tags:
- kubernetes
- k8s
install: |
  github_get_releases stepro/kdo | \
      jq --raw-output '.[].tag_name' | \
      sort --version-sort --reverse | \
      head -n 1 | \
      xargs -I{} curl --silent https://api.github.com/repos/stepro/kdo/releases/tags/{} | \
      github_resolve_assets | \
      github_select_asset_by_suffix -linux-amd64.tar.gz | \
      github_get_asset_download_url | \
      download_file | \
      untar_file kdo
