name: asciigraph
description: Go package to make lightweight ASCII line graph in command line apps with no other dependencies
repo: guptarohit/asciigraph
version:
  latest: v0.5.1 # renovate: datasource=github-releases depName=guptarohit/asciigraph
tags:
  - shell
install:
  script: |-
    github_install \
        --repo guptarohit/asciigraph \
        --match suffix \
        --asset _Linux_x86_64.tar.gz \
        --type tarball \
        --include asciigraph
