name: clusterlint
description: A best practices checker for Kubernetes clusters
repo: digitalocean/clusterlint
version:
  latest: v0.2.4 # renovate: datasource=github-releases depName=digitalocean/clusterlint
  command: clusterlint --version
  filter: ^clusterlint
  pattern: s/^(.+)$/v\1/
tags:
  - kubernetes
  - k8s
  - lint
  - quality
install:
  script: |-
    github_install \
        --repo digitalocean/clusterlint \
        --match suffix \
        --asset -linux-amd64.tar.gz \
        --type tarball \
        --include ./clusterlint
