name: dockly
description: Immersive terminal interface for managing docker containers and services
repo: lirantal/dockly
version:
  latest: v3.17.1 # renovate: datasource=github-releases depName=lirantal/dockly
  command: dockly --version
  filter: ^dockly
  pattern: s/^dockly\s(\S+)\s.+$/v\1/
tags:
  - docker
  - container
  - interface
  - ui
install:
  script: install_node_module dockly
