name: argocd
description: Declarative continuous deployment for Kubernetes
repo: argoproj/argo-cd
version:
  latest: v1.7.8 # renovate: datasource=github-releases depName=argoproj/argo-cd
  command: argocd version
  filter: argocd
  pattern: ^argocd:\s(.+)\+.+$
tags:
- gitops
- kubernetes
- k8s
