name: argocd
description: Declarative continuous deployment for Kubernetes
repo: argoproj/argo-cd
version:
  command: argocd version
  filter: argocd
  pattern: ^argocd:\s(.+)\+.+$
tags:
- gitops
- kubernetes
- k8s
