name: cfssl
description: Cloudflare's PKI and TLS toolkit
repo: cloudflare/cfssl
version:
  latest: v1.5.0 # renovate: datasource=github-releases depName=cloudflare/cfssl
  command: cfssl version
  filter: ^Version
  pattern: s/^Version:\s(.+)$/v\1/
tags:
  - certificate
  - ssl
  - tls
  - pki
install:
  script: |-
    github_get_release cloudflare/cfssl | \
        github_resolve_assets | \
        github_select_asset_by_suffix _linux_amd64 | \
        run_tasks \
            "\
                github_select_asset_by_prefix cfssl_ | \
                github_get_asset_download_url | \
                download_file | \
                store_file cfssl | \
                make_executable \
            " \
            "\
                github_select_asset_by_prefix cfssljson_ | \
                github_get_asset_download_url | \
                download_file | \
                store_file cfssljson | \
                make_executable \
            "
