name: cfssl
description: Cloudflare's PKI and TLS toolkit
repo: cloudflare/cfssl
version:
  latest: v1.5.0 # renovate: datasource=github-releases depName=cloudflare/cfssl
tags:
- certificate
- ssl
- tls
- pki
