name: cfssl
description: Cloudflare's PKI and TLS toolkit
repo: cloudflare/cfssl
version:
  latest: v1.5.0 # renovate: datasource=github-releases depName=cloudflare/cfssl
  command: cfssl version
  filter: ^Version
  pattern: s/^Version:\s(.+)$/v\1/
tags:
- certificate
- ssl
- tls
- pki
