name: ktunnel
description: A cli that exposes your local resources to kubernetes
repo: omrikiei/ktunnel
version:
  latest: v1.3.1 # renovate: datasource=github-releases depName=omrikiei/ktunnel
  command: ktunnel --version 2>/dev/null
  filter: ^ktunnel
  pattern: s/^ktunnel\sversion\s(.+)$/v\1/
tags:
  - kubernetes
  - k8s
install:
  script: |-
    github_install \
        --repo omrikiei/ktunnel \
        --match suffix \
        --asset _Linux_x86_64.tar.gz \
        --type tarball \
        --include ktunnel
