name: powerline-go
description: A beautiful and useful low-latency prompt for your shell, written in go
repo: justjanne/powerline-go
version:
  latest: v1.18.0 # renovate: datasource=github-releases depName=justjanne/powerline-go
tags:
- powerline
- shell
- prompt
files:
- theme.json
