name: hetzner-kube
description: A CLI tool for provisioning kubernetes clusters on Hetzner Cloud
repo: xetys/hetzner-kube
version:
  latest: 0.5.1 # renovate: datasource=github-releases depName=xetys/hetzner-kube
  command: hetzner-kube version
  filter: ^[[:digit:]]
  pattern: s/^(.+)$/\1/
tags:
  - kubernetes
  - k8s
  - hetzner
  - cloud
  - cluster
  - bootstrap
install:
  script: |-
    github_install \
        --repo xetys/hetzner-kube \
        --match suffix \
        --asset -linux-amd64 \
        --type binary \
        --name hetzner-kube

    hetzner-kube completion bash | \
        store_completion hetzner-kube
