name: gvm
description: Go Version Manager
repo: moovweb/gvm
version:
  latest: 1.0.22 # renovate: datasource=github-releases depName=moovweb/gvm
  command: gvm version
  filter: ^Go\sVersion\sManager\s
  pattern: s/^Go\sVersion\sManager\sv(\S+)\s.+$/\1/
tags:
- go
- golang
- version
- manager
- version manager
files:
- name: Dockerfile
  content: |
    FROM ubuntu:20.04@sha256:1d7b639619bdca2d008eca2d5293e3c43ff84cbee597ff76de3b7a7de3e84956
    ENV DEBIAN_FRONTEND=noninteractive
    RUN apt-get update \
    && apt-get -y install \
            curl \
            git \
            mercurial \
            make \
            binutils \
            bison \
            gcc \
            build-essential
- name: profile.d.gvm.sh
  content: |
    #!/bin/bash
    export GVM_ROOT="${TARGET_BASE}/gvm"
    source "${GVM_ROOT}/scripts/gvm-default"

