name: gvm
description: Go Version Manager
repo: moovweb/gvm
version:
  latest: 1.0.22 # renovate: datasource=github-releases depName=moovweb/gvm
tags:
- go
- golang
- version
- manager
- version manager
files:
- Dockerfile
