name: helm-docs
description: A tool for automatically generating markdown documentation for helm charts
repo: norwoodj/helm-docs
version:
  latest: v1.4.0 # renovate: datasource=github-releases depName=norwoodj/helm-docs
  command: helm-docs --version
  filter: ^helm-docs
  pattern: s/^helm-docs\sversion\s(.+)$/v\1/
tags:
  - kubernetes
  - k8s
  - package
  - template
  - substituton
  - expansion
  - configuration
install:
  script: |-
    github_install \
        --repo norwoodj/helm-docs \
        --match suffix \
        --asset _Linux_x86_64.tar.gz \
        --type tarball \
        --include helm-docs
