name: node
description: Node.js JavaScript runtime
repo: nodejs/node
version:
  latest: v14.15.0 # renovate: datasource=github-releases depName=nodejs/node
  command: node --version
  filter: ^v
  pattern: s/^(.+)$/\1/
tags:
- node
- nodejs
- javascript
- typescript
