name: dive
description: A tool for exploring each layer in a docker image
repo: wagoodman/dive
version:
  latest: v0.9.2 # renovate: datasource=github-releases depName=wagoodman/dive
tags:
- docker
- container
- layers
- images
- quality
