name: cnitool
description: A simple program that executes a CNI configuration
repo: containernetworking/cni
links:
  - text: Usage
    url: https://github.com/containernetworking/cni/tree/master/cnitool
version:
  latest: v0.8.0 # renovate: datasource=github-releases depName=containernetworking/cni
tags:
  - kubernetes
  - k8s
  - network
  - plugin
  - cni
install:
  docker: true
  script: |-
    build_containerized golang <<EOF
    go get github.com/containernetworking/cni/cnitool
    go install github.com/containernetworking/cni/cnitool
    cp /go/bin/cnitool /
    EOF
    extract_file_from_container cnitool
