name: vault
description: A tool for secrets management, encryption as a service, and privileged access management
repo: hashicorp/vault
version:
  latest: v1.5.5 # renovate: datasource=github-tags depName=hashicorp/vault
  command: vault --version
  filter: ^Vault
  pattern: s/^Vault\s(\S+)\s.+$/\1/
tags:
- security
- secrets
install: |
  echo "https://releases.hashicorp.com/vault/${requested_version#v}/vault_${requested_version#v}_linux_amd64.zip" | \
      download_file | \
      store_file "vault.zip" "${temporary_directory}"
  unzip_file "${temporary_directory}/vault.zip"
  ${SUDO} mv vault "${TARGET_BIN}"
