name: ctop
description: Top-like interface for container metrics
repo: bcicen/ctop
links:
  - text: Homepage
    url: https://ctop.sh/
version:
  latest: v0.7.5 # renovate: datasource=github-releases depName=bcicen/ctop
  command: ctop -v
  filter: ^ctop
  pattern: s/^ctop\sversion\s(\S+),.+$/v\1/
tags:
  - shell
  - terminal
  - monitor
  - performance
install:
  script: |-
    github_install \
        --repo bcicen/ctop \
        --match suffix \
        --asset -linux-amd64 \
        --type binary \
        --name ctop
