name: pyenv
description: A beautiful and useful low-latency prompt for your shell, written in go
repo: pyenv/pyenv
links:
- text: pyenv-virtualenv
  url: https://github.com/pyenv/pyenv-virtualenv
- text: Suggested build environment
  url: https://github.com/pyenv/pyenv/wiki#suggested-build-environment
version:
  latest: v1.2.21 # renovate: datasource=github-releases depName=pyenv/pyenv
tags:
- python
- version
- manager
- version manager
files:
- Dockerfile
