name: pyenv
description: A beautiful and useful low-latency prompt for your shell, written in go
repo: pyenv/pyenv
links:
  - text: pyenv-virtualenv
    url: https://github.com/pyenv/pyenv-virtualenv
  - text: Suggested build environment
    url: https://github.com/pyenv/pyenv/wiki#suggested-build-environment
version:
  latest: v1.2.21 # renovate: datasource=github-releases depName=pyenv/pyenv
  command: pyenv --version
  filter: ^pyenv
  pattern: s/^pyenv\s(.+)$/v\1/
tags:
  - python
  - version
  - manager
  - version manager
files:
  - name: Dockerfile
    content: |
      FROM ubuntu:20.04@sha256:1d7b639619bdca2d008eca2d5293e3c43ff84cbee597ff76de3b7a7de3e84956
      ENV DEBIAN_FRONTEND=noninteractive
      RUN apt-get update \
      && apt-get -y install \
              build-essential \
              libssl-dev \
              zlib1g-dev \
              libbz2-dev \
              libreadline-dev \
              libsqlite3-dev \
              wget \
              curl \
              llvm \
              libncurses5-dev \
              libncursesw5-dev \
              xz-utils \
              tk-dev \
              libffi-dev \
              liblzma-dev \
              python-openssl \
              git \
              libedit-dev
  - name: profile.d.pyenv.sh
    content: |
      #!/bin/bash
      export PYENV_ROOT="${TARGET_BASE}/pyenv"
      export PATH="${PYENV_ROOT}/bin:${PATH}"
install:
  docker: true
  script: |-
    ${SUDO} mkdir -p "${TARGET_BASE}/pyenv"
    echo "https://github.com/pyenv/pyenv/archive/${requested_version}.tar.gz" | \
        download_file | \
        tar -xzC "${TARGET_BASE}/pyenv" --strip-components=1
    export PYENV_ROOT="${TARGET_BASE}/pyenv"
    export PATH="${PYENV_ROOT}/bin:${PATH}"

    ${SUDO} mkdir -p "${PYENV_ROOT}/plugins/pyenv-virtualenv"
    echo "https://github.com/pyenv/pyenv-virtualenv/archive/master.tar.gz" | \
        download_file | \
        tar -xzC "${PYENV_ROOT}/plugins/pyenv-virtualenv" --strip-components=1
    
    ${SUDO} mkdir -p "${TARGET_BASE}/pyenv/pyenv-doctor"
    echo "https://github.com/pyenv/pyenv-doctor/archive/master.tar.gz" | \
        download_file | \
        tar -xzC "${PYENV_ROOT}/plugins/pyenv-doctor" --strip-components=1

    export DOCKER_BUILDKIT=1
    get_file pyenv Dockerfile | \
        docker build --tag pyenv -

    docker run --rm --name pyenv \
        --env PYENV \
        --env PATH \
        --volume "${TARGET_BASE}/pyenv:${TARGET_BASE}/pyenv" \
        pyenv \
        pyenv doctor

    get_file pyenv profile.d.pyenv.sh | \
        TARGET_BASE="${TARGET_BASE}" envsubst '${TARGET_BASE}' | \
        store_file pyenv.sh /etc/profile.d
