name: go
description: The Go programming language
repo: golang/go
version:
  latest: go1.15.3 # renovate: datasource=github-tags depName=golang/go versioning=regex:^go(?<major>\d+)\\.(?<minor>\d+)\\.(?<patch>\d+)$
tags:
- go
