name: rakkess
description: Review Access - kubectl plugin to show an access matrix for k8s server resources
repo: corneliusweig/rakkess
version:
  latest: v0.4.5 # renovate: datasource=github-releases depName=corneliusweig/rakkess
tags:
- kubernetes
- k8s
- rbac
- security
- plugin
- kubectl
