name: kube-ps1
description: Kubernetes prompt info for bash and zsh
repo: jonmosco/kube-ps1
version:
  latest: v0.7.0 # renovate: datasource=github-releases depName=jonmosco/kube-ps1
tags:
- kubernetes
- k8s
- shell
- prompt
files:
- profile.d.kube-ps1.sh
