name: kube-ps1
description: Kubernetes prompt info for bash and zsh
repo: jonmosco/kube-ps1
version:
  latest: v0.7.0 # renovate: datasource=github-releases depName=jonmosco/kube-ps1
tags:
- kubernetes
- k8s
- shell
- prompt
install: |
  build_containerized alpine sh -xe <<EOF
  apk add --update-cache --no-cache git curl jq
  git clone https://github.com/jonmosco/kube-ps1
  cd kube-ps1
  curl --silent https://api.github.com/repos/jonmosco/kube-ps1/releases/latest | jq --raw-output '.tag_name' | xargs git checkout
  cp kube-ps1.sh /
  EOF
  extract_file_from_container kube-ps1.sh

  get_file kube-ps1 profile.d.kube-ps1.sh | \
      store_file kube-ps1.sh /etc/profile.d
files:
- name: profile.d.kube-ps1.sh
  content: |
    #!/bin/bash
    source /usr/local/bin/kube-ps1.sh
    PS1='[\u@\h \W $(kube_ps1)]\$ '
