name: act
description: Run your GitHub Actions locally
repo: nektos/act
version:
  latest: 0.2.14 # renovate: datasource=github-releases depName=nektos/act
  command: act --version
  filter: act
  pattern: ^act\sversion\s(.+)$
tags:
- pipeline
- continuous
- ci/cd
- integration
- delivery
- deployment
- container
