name: act
description: Run your GitHub Actions locally
repo: nektos/act
version:
  command: act --version
  filter: act
  pattern: ^act\sversion\s(.+)$
tags:
- pipeline
- continuous
- ci/cd
- integration
- delivery
- deployment
- container
