name: minikube
description: Run Kubernetes locally
repo: kubernetes/minikube
links:
- text: Homepage
  url: https://minikube.sigs.k8s.io/
- text: Handbook
  url: https://minikube.sigs.k8s.io/docs/handbook/
version:
  latest: v1.15.1 # renovate: datasource=github-releases depName=kubernetes/minikube
  command: minikube version
  filter: ^minikube
  pattern: s/^minikube\sversion:\s(.+)$/\1/
tags:
  - kubernetes
  - k8s
  - container
install:
  script: |-
    github_install \
        --repo kubernetes/minikube \
        --match name \
        --asset minikube-linux-amd64 \
        --type binary \
        --name minikube

    minikube completion bash | \
        store_completion minikube
