name: python
description: The Python programming language
repo: python/cpython
version:
  latest: v3.9.0 # renovate: datasource=github-tags depName=python/cpython
  command: python3 --version
  filter: ^Python
  pattern: s/^Python\s(.+)$/v\1/
tags:
- python
- py
