name: python
description: The Python programming language
repo: python/cpython
version:
  latest: v3.9.0 # renovate: datasource=github-tags depName=python/cpython
  command: python3 --version
  filter: ^Python
  pattern: s/^Python\s(.+)$/v\1/
tags:
  - python
  - py
install:
  docker: true
  script: |-
    require pyenv
    source /etc/profile.d/pyenv.sh

    docker run --rm --name pyenv \
        --env PYENV_ROOT \
        --env PATH \
        --volume "${PYENV_ROOT}:${PYENV_ROOT}" \
        pyenv \
        pyenv install "${requested_version#v}" --skip-existing
    ${SUDO} bash -c "source /etc/profile.d/pyenv.sh; ${PYENV_ROOT}/bin/pyenv rehash"
    ${SUDO} bash -c "source /etc/profile.d/pyenv.sh; ${PYENV_ROOT}/bin/pyenv global ${requested_version#v}"
