name: lab
description: Lab wraps Git or Hub, making it simple to clone, fork, and interact with repositories on GitLab
repo: zaquestion/lab
version:
  latest: v0.17.2 # renovate: datasource=github-releases depName=zaquestion/lab
tags:
- gitlab
- pipeline
- continuous
- ci/cd
- integration
- delivery
- deployment
