name: termtosvg
description: (UNMAINTAINED) Record terminal sessions as SVG animations
repo: nbedos/termtosvg
version:
  latest: 1.1.0 # renovate: datasource=github-releases depName=nbedos/termtosvg
tags:
  - shell
  - record
  - cast
  - screen
install:
  script: install_python_module termtosvg==${requested_version}
