name: cheat
description: cheat allows you to create and view interactive cheatsheets on the command-line
repo: cheat/cheat
version:
  latest: 4.1.1 # renovate: datasource=github-releases depName=cheat/cheat
  command: cheat --version
  filter: ^[[:digit:]]
  pattern: s/^(.+)$/\1/
tags:
  - shell
  - help
  - support
  - man
  - manpage
install:
  script: |-
    github_install \
        --repo cheat/cheat \
        --match name \
        --asset cheat-linux-amd64.gz \
        --type gunzip \
        --name cheat

    mkdir -p "${HOME}/.config/cheat/cheatsheets/personal"
    cheat --init > "${HOME}/.config/cheat/conf.yml"
    
    if ! test -d "${HOME}/.config/cheat/cheatsheets/community"; then
        git clone https://github.com/cheat/cheatsheets "${HOME}/.config/cheat/cheatsheets/community"
    else
        cd "${HOME}/.config/cheat/cheatsheets/community"
        git pull
    fi
