name: podman
description: A tool for managing OCI containers and pods
repo: containers/podman
version:
  latest: v2.1.1 # renovate: datasource=github-releases depName=containers/podman
  command: podman --version
  filter: ^podman
  pattern: s/^podman\sversion\s(.+)$/v\1/
tags:
- container
install: |
  github_install \
      --repo containers/podman \
      --match name \
      --asset podman-remote-static.tar.gz \
      --type tarball \
      --include podman-remote-static

  rename_file podman-remote-static podman
