name: age
description: A simple, modern and secure encryption tool (and Go library) with small explicit keys, no config options, and UNIX-style composability
repo: FiloSottile/age
version:
  latest: v1.0.0-beta5 # renovate: datasource=github-tags depName=FiloSottile/age versioning=regex:^v(?<major>\d+?)\.(?<minor>\d+?)\.(?<patch>\d+?)(-(?<prerelease>.+?))?$
tags:
  - encryption
  - security
install:
  docker: true
  script: |-
    build_containerized golang <<EOF
    curl -sL "https://github.com/FiloSottile/age/archive/${requested_version}.tar.gz" | \
        tar -xz /tmp/age --strip-components=1
    cd /tmp/age
    go build -o . filippo.io/age/cmd/...
    cp age age-keygen /
    EOF
    extract_file_from_container age age-keygen
