name: age
description: A simple, modern and secure encryption tool (and Go library) with small explicit keys, no config options, and UNIX-style composability
repo: FiloSottile/age
tags:
- encryption
- security
