name: k
description: Experimental wrapper for kubectl
repo: rothgar/k
version:
  latest: 0.3.4 # renovate: datasource=github-releases depName=rothgar/k
tags:
- kubernetes
- k8s
- kubectl
- namespace
- context
