name: k
description: Experimental wrapper for kubectl
repo: rothgar/k
version:
  latest: 0.3.4 # renovate: datasource=github-releases depName=rothgar/k
  command: k
  filter: ^[[:space:]]*k[[:space:]]version
  pattern: s/^\s+k\sversion:\s+(.+)$/\1/
tags:
- kubernetes
- k8s
- kubectl
- namespace
- context
install: |
  github_get_release rothgar/k | \
      github_resolve_assets | \
      github_select_asset_by_suffix _Linux_x86_64.tar.gz | \
      github_get_asset_download_url | \
      download_file \
      >"${temporary_directory}/k.tar.gz"

  ${SUDO} tar -xz -f "${temporary_directory}/k.tar.gz" -C "${TARGET_BIN}" --strip-components=1 bin/k

  ${SUDO} tar -xz -f "${temporary_directory}/k.tar.gz" -C "${TARGET_COMPLETION}" --strip-components=2 completions/bash/k
  ${SUDO} mv "${TARGET_COMPLETION}/k" "${TARGET_COMPLETION}/k.sh"
