name: manifest-tool
description: Manifest tool for manifest list object creation/query
repo: estesp/manifest-tool
version:
  latest: v1.0.3 # renovate: datasource=github-releases depName=estesp/manifest-tool
  command: manifest-tool --version
  filter: ^manifest-tool
  pattern: s/^manifest-tool\sversion\s(\S+)\s.+$/v\1/
tags:
- docker
- container
- image
- registry
- platform
- architecture
