name: kube-advise-psp
description: Help building an adaptive and fine-grained pod security policy
repo: sysdiglabs/kube-psp-advisor
version:
  latest: v2.0.0 # renovate: datasource=github-releases depName=sysdiglabs/kube-psp-advisor
tags:
- kubernetes
- k8s
- security
- policy
install: |
  github_get_release sysdiglabs/kube-psp-advisor | \
      github_resolve_assets | \
      github_select_asset_by_suffix _linux_amd64.tar.gz | \
      github_get_asset_download_url | \
      download_file | \
      untar_file kubectl-advise-psp
  rename_file kubectl-advise-psp kube-advise-psp
