name: umoci
description: umoci modifies Open Container images
repo: opencontainers/umoci
links:
- text: Homepage
  url: https://umo.ci/
version:
  latest: v0.4.6 # renovate: datasource=github-releases depName=opencontainers/umoci
tags:
- container
- image
- oci
