name: vendir
description: Easy way to vendor portions of git repos, github releases, etc. declaratively
repo: k14s/vendir
links:
- text: Homepage
  url: https://carvel.dev/
version:
  latest: v0.11.0 # renovate: datasource=github-releases depName=k14s/vendir  
tags:
- shell
