name: cue
description: Validate and define text-based and dynamic configuration
repo: cuelang/cue
links:
- text: Homepage
  url: https://cuelang.org/
version:
  latest: v0.2.2 # renovate: datasource=github-releases depName=cuelang/cue
tags:
- configuration
