name: linuxkit
description: A toolkit for building secure, portable and lean operating systems for containers
repo: linuxkit/linuxkit
version:
  latest: v0.8 # renovate: datasource=github-releases depName=linuxkit/linuxkit versioning=loose
  command: linuxkit version
  filter: ^linuxkit
  pattern: s/^linuxkit\sversion\s(.+)$/\1/
tags:
- container
- moby
install: |
  github_install \
      --repo linuxkit/linuxkit \
      --match name \
      --asset linuxkit-linux-amd64 \
      --type binary \
      --name linuxkit
