name: wslu
description: A collection of utilities for Windows 10 Linux Subsystems
repo: wslutilities/wslu
version:
  latest: v3.2.1 # renovate: datasource=github-releases depName=wslutilities/wslu
tags:
  - wsl
install:
  script: |-
    git clone https://github.com/wslutilities/wslu "${temporary_directory}"
    git checkout "${requested_version}"
    ${SUDO} PREFIX=/usr/local make all install
