name: hub
description: A command-line tool that makes git easier to use with GitHub
repo: github/hub
version:
  latest: v2.14.2 # renovate: datasource=github-releases depName=github/hub
  command: hub --version
  filter: ^hub
  pattern: s/^hub\sversion\s(.+)$/v\1/
tags:
- github
install: |
  github_get_release github/hub | \
      github_resolve_assets | \
      run_tasks \
          "\
              github_select_asset_by_prefix hub-linux-amd64- | \
              github_get_asset_download_url | \
              download_file | \
              ${SUDO} tar -xzC ${TARGET_BASE} --wildcards --strip-components=1 */bin/hub
          " \
          "\
              github_select_asset_by_prefix hub-linux-amd64- | \
              github_get_asset_download_url | \
              download_file | \
              ${SUDO} tar -xzC ${TARGET_COMPLETION} --wildcards --strip-components=2 */etc/hub.bash_completion.sh
          "
