name: ignite
description: Ignite a Firecracker microVM
repo: weaveworks/ignite
links:
  - text: Documentation
    url: https://ignite.readthedocs.org/
version:
  latest: v0.8.0 # renovate: datasource=github-releases depName=weaveworks/ignite
  command: ignite version --output short
  filter: ^v
  pattern: s/^(.+)$/\1/
tags:
  - serverless
  - virtual machine
  - vm
  - container
  - gitops
  - firecracker
install:
  script: |-
    require wsl2-kernel
    require cni

    if ! cat /proc/config.gz | gunzip | grep --quiet CONFIG_KVM=y || ! cat /proc/config.gz | gunzip | grep --quiet CONFIG_KVM_INTEL=y; then
        echo "ERROR: KVM is not configured in your kernel"
        exit 1
    fi

    if ! cat /proc/config.gz | gunzip | grep --quiet CONFIG_DM_ZERO=y || ! cat /proc/config.gz | gunzip | grep --quiet CONFIG_DM_SNAPSHOT=y; then
        echo "ERROR: Device mapper is not correctly configured in your kernel"
        exit 1
    fi

    github_get_release weaveworks/ignite "${requested_version}" | \
        github_resolve_assets | \
        run_tasks \
            "\
                github_select_asset_by_prefix ignite- | \
                github_select_asset_by_suffix -amd64 | \
                github_get_asset_download_url | \
                download_file | \
                store_file ignite | \
                make_executable \
            " \
            "\
                github_select_asset_by_prefix ignited- | \
                github_select_asset_by_suffix -amd64 | \
                github_get_asset_download_url | \
                download_file | \
                store_file ignited | \
                make_executable \
            "

    ignite completion | \
        store_completion ignite
