name: runc
description: CLI tool for spawning and running containers according to the OCI specification
repo: opencontainers/runc
links:
  - text: Runtime spec
    url: https://github.com/opencontainers/runtime-spec
version:
  latest: v1.0.0-rc92 # renovate: datasource=github-releases depName=opencontainers/runc
  command: runc --version
  filter: ^runc
  pattern: s/^runc\sversion\s(.+)$/v\1/
tags:
  - container
  - oci
install:
  script: |-
    github_install \
        --repo opencontainers/runc \
        --match name \
        --asset runc.amd64 \
        --type binary \
        --name runc
