name: whalebrew
description: Homebrew, but with Docker images
repo: whalebrew/whalebrew
version:
  latest: 0.2.5 # renovate: datasource=github-releases depName=whalebrew/whalebrew
  command: whalebrew version
  filter: ^Whalebrew
  pattern: s/^Whalebrew\s(.+)$/\1/
tags:
  - container
install:
  script: |-
    github_install \
        --repo whalebrew/whalebrew \
        --match name \
        --asset whalebrew-Linux-x86_64 \
        --type binary \
        --name whalebrew
