on:
  schedule:
  - cron: '*/15 * * * *'

name: Auto release packages

jobs:
  build:
    name: Auto release packages
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare release
        run: |
          RELEASE=false
          BUMP=patch

          TIMESTAMP="$(
              curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest" \
                    --silent \
                    --location \
                    --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
                  jq --raw-output .created_at
          )"

          RENOVATE_PR_COUNT="$(
              curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues?state=closed&since=${TIMESTAMP}&labels=type/renovate" \
                      --silent \
                      --location \
                      --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
                  jq '.[].number' | \
                  wc -l
          )"
          if test "${RENOVATE_PR_COUNT}" -gt 0; then
              echo "Found closed pull requests. Will release a patch (at least)."
              RELEASE=true
              BUMP=patch
          fi

          PACKAGE_ISSUE_COUNT="$(
              curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues?state=closed&since=${TIMESTAMP}&labels=component/package" \
                      --silent \
                      --location \
                      --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
                  jq '.[].number' | \
                  wc -l
          )"
          if test "${PACKAGE_ISSUE_COUNT}" -gt 0; then
              echo "Found closed issues. Will release a minor version."
              RELEASE=true
              BUMP=minor
          fi

          if ${RELEASE}; then
              make "bump-${BUMP}"
          fi
