on:
  pull_request:
    types:
    - opened

name: Test package

jobs:
  build:
    name: Test package
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printenv
