name: fluxctl
description: The GitOps Kubernetes operator
repo: fluxcd/flux
links:
- text: Homepage
  url: https://fluxcd.io/
version:
  latest: 1.21.0 # renovate: datasource=github-releases depName=fluxcd/flux
tags:
- gitops
- kubernetes
- k8s
