name: mkdocs
description: Project documentation with Markdown
repo: mkdocs/mkdocs
version:
  latest: 1.1.2 # renovate: datasource=github-tags depName=mkdocs/mkdocs
tags:
  - documentation
install:
  script: |-
    install_python_module mkdocs
